### ISSUE TITLE
Use of network connection closed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#136]
**Expected behavior**
Should be able to run specifications seamlessly

**Actual behavior**
Getting `Use of network connection closed`

**Steps to replicate**
* Run project [basic.zip](https://github.com/getgauge/gauge-js/files/1859004/basic9.zip)
> Observe the error Failed to initialize scenario datastore. Error: write tcp 127.0.0.1:56353->127.0.0.1:56355: use of closed network connection

**Comment by sguptatw** [comment]
Another scenario when this error was observed was on `textDocument/didOpen`

```
<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\node_modules\protobufjs\src\reader.js:94
            throw indexOutOfRange(this, 10);
            ^

RangeError: index out of range: 1460 + 10 > 1460
    at indexOutOfRange (<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\node_modules\protobufjs\src\reader.js:13:12)
    at BufferReader.read_uint32 [as uint32] (<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\node_modules\protobufjs\src\reader.js:94:19)
    at Type.CacheFileRequest$decode [as decode] (eval at Codegen (<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:8:11)
    at Type.Message$decode [as decode] (eval at Codegen (<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:89:32)
    at Type.decodeDelimited (<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\node_modules\protobufjs\src\type.js:520:17)
    at Socket.messageHandler (<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\src\connection.js:20:49)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)

```

**Comment by sguptatw** [comment]
Another scenario when this error was observed was after `textDocument/didOpen`

```
<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\node_modules\protobufjs\src\reader.js:94
            throw indexOutOfRange(this, 10);
            ^

RangeError: index out of range: 1460 + 10 > 1460
    at indexOutOfRange (<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\node_modules\protobufjs\src\reader.js:13:12)
    at BufferReader.read_uint32 [as uint32] (<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\node_modules\protobufjs\src\reader.js:94:19)
    at Type.CacheFileRequest$decode [as decode] (eval at Codegen (<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:8:11)
    at Type.Message$decode [as decode] (eval at Codegen (<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:89:32)
    at Type.decodeDelimited (<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\node_modules\protobufjs\src\type.js:520:17)
    at Socket.messageHandler (<user>\AppData\Roaming\gauge\plugins\js\2.2.0.nightly-2018-03-29\src\connection.js:20:49)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)

12:45:37.306 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/diagnostics/circular-references.spec","diagnostics":[{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":11,"character":0},"end":{"line":11,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.306 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/diagnostics/concept-diagnostics.spec","diagnostics":[{"range":{"start":{"line":14,"character":0},"end":{"line":14,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.306 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/generate/generateConcepts/generateConcepts.spec","diagnostics":[{"range":{"start":{"line":2,"character":0},"end":{"line":2,"character":60}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":83}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":29}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.306 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/codelens/findUsages.spec","diagnostics":[{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":11,"character":0},"end":{"line":11,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":15,"character":0},"end":{"line":15,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":19,"character":0},"end":{"line":19,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":23,"character":0},"end":{"line":23,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.306 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/codecompletion/parameters.spec","diagnostics":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":2,"character":0},"end":{"line":2,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":9,"character":0},"end":{"line":9,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":10,"character":0},"end":{"line":10,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":22,"character":0},"end":{"line":22,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":23,"character":0},"end":{"line":23,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":31,"character":0},"end":{"line":31,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":32,"character":0},"end":{"line":32,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":33,"character":0},"end":{"line":33,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":34,"character":0},"end":{"line":34,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":43,"character":0},"end":{"line":43,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.306 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/codecompletion/steps.spec","diagnostics":[{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":17,"character":0},"end":{"line":17,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":18,"character":0},"end":{"line":18,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.306 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/codelens/runLinks.spec","diagnostics":[{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":8,"character":0},"end":{"line":8,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":12,"character":0},"end":{"line":12,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":13,"character":0},"end":{"line":13,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.306 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/diagnostics/format.spec","diagnostics":[{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.306 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/project.cpt","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.306 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/gotodefinition/goto%!a(MISSING)%!c(MISSING)oncept.spec","diagnostics":[{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.307 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/generate/generateStubs/generateStubs.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":12,"character":0},"end":{"line":12,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.307 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/diagnostics/duplicate%!d(MISSING)iagnostics.spec","diagnostics":[{"range":{"start":{"line":10,"character":0},"end":{"line":10,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.307 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/diagnostics/specification%!d(MISSING)iagnostics.spec","diagnostics":[{"range":{"start":{"line":14,"character":0},"end":{"line":14,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.307 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/gotodefinition/goto%!a(MISSING)%!s(MISSING)tep%!d(MISSING)efinition.spec","diagnostics":[{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":11,"character":0},"end":{"line":11,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":12,"character":0},"end":{"line":12,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.307 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/playback.spec","diagnostics":[{"range":{"start":{"line":3,"character":0},"end":{"line":3,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.307 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/rename/refactor.spec","diagnostics":[{"range":{"start":{"line":2,"character":0},"end":{"line":2,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":10,"character":0},"end":{"line":10,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":11,"character":0},"end":{"line":11,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.307 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/testexplorer/listOfSpecs.spec","diagnostics":[{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.307 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/specs/codecompletion/tags.spec","diagnostics":[{"range":{"start":{"line":8,"character":0},"end":{"line":8,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"},{"range":{"start":{"line":9,"character":0},"end":{"line":9,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:57862-\u003e127.0.0.1:57866: use of closed network connection"}]}
12:45:37.385 --> request #845: textDocument/codeLens: {"textDocument":{"uri":"file:///c%!A(MISSING)/work/getgauge/FT/gauge-lsp-tests/tests/util/fileExtension.js"}}
12:45:37.386 request #845: textDocument/codeLens: Error while connecting to runner : write tcp 127.0.0.1:57862->127.0.0.1:57866: use of closed network connection
```

**Comment by sguptatw** [comment]
Observed on CI [Logs](https://build.getgauge.io/go/files/JS-LSP-Tests/412/tests/1/linux-js-no-wd/logs/logs/lsp-tests/Should+list+steps+implemented+but+unused+steps/lsp.log) for the run [Linux-js](https://build.getgauge.io/go/tab/build/detail/JS-LSP-Tests/413/tests/1/linux-js)
```
01:17:38.163 Gauge Install ID: 934110e3-0d76-4b08-992d-35829b58f9cb
01:17:38.164 Watching directory: /godata/pipelines/JS-LSP-Tests/data/steps-codecomplete/specs
01:17:38.164 Initializing concepts cache with 0 concepts
01:17:38.164 Found 2 files
01:17:38.165 Initializing specs cache with 2 specs
01:17:38.165 Adding specs from /godata/pipelines/JS-LSP-Tests/data/steps-codecomplete/specs/codecomplete_step.spec
01:17:38.165 Adding specs from /godata/pipelines/JS-LSP-Tests/data/steps-codecomplete/specs/codecomplete_param.spec
01:17:38.165 Initializing steps cache with 2 steps
01:17:38.166 Starting language runner
01:17:38.514 LangServer: reading on stdin, writing on stdout
01:17:38.515 --> request #0: initialize: {"processId":445,"rootPath":"/godata/pipelines/JS-LSP-Tests/data/steps-codecomplete","rootUri":"file:///godata/pipelines/JS-LSP-Tests/data/steps-codecomplete","capabilities":{"workspace":{"applyEdit":true,"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true}},"textDocument":{"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true}},"hover":{"dynamicRegistration":true},"signatureHelp":{"dynamicRegistration":true},"definition":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true},"codeAction":{"dynamicRegistration":true},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true}}},"trace":"off","experimental":{}}
01:17:38.516 <-- result #0: initialize: {"capabilities":{"textDocumentSync":1,"completionProvider":{"resolveProvider":true,"triggerCharacters":["*","* ","\"","\u003c",":",","]},"definitionProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{},"documentFormattingProvider":true,"renameProvider":true}}
01:17:38.516 --> notif: initialized: {}
01:17:38.517 <-- request #0: client/registerCapability: {"registrations":[{"id":"gauge-fileWatcher","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"/godata/pipelines/JS-LSP-Tests/data/steps-codecomplete/**/*{.cpt,.spec,.md}","kind":5}]}}]}
01:17:38.517 --> result #0: client/registerCapability: null
01:17:38.520 --> request #1: gauge/getRunnerLanguage: null
01:17:38.520 <-- result #1: gauge/getRunnerLanguage: "javascript"
01:17:38.522 --> notif: textDocument/didOpen: {"textDocument":{"uri":"file:///godata/pipelines/JS-LSP-Tests/data/steps-codecomplete/specs/codecomplete_step.spec","languageId":"markdown","version":1,"text":"Steps code complete\n=====================\nGauge LSP 2\n-----------\n* unimplemented step one\n* implemented step one\n* unimplemented step two"}}
01:17:38.536 notif #0: initialized: Connection closed [127.0.0.1:36616] cause: read tcp 127.0.0.1:40738->127.0.0.1:36616: read: connection reset by peer
01:17:38.536 <-- notif: window/logMessage: {"type":1,"message":"notif #0: initialized: Connection closed [127.0.0.1:36616] cause: read tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: read: connection reset by peer"}
01:17:38.537 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///godata/pipelines/JS-LSP-Tests/data/steps-codecomplete/specs/codecomplete_param.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"message":"Connection closed [127.0.0.1:36616] cause: read tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"},{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"},{"range":{"start":{"line":8,"character":0},"end":{"line":8,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"},{"range":{"start":{"line":9,"character":0},"end":{"line":9,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"}]}
01:17:38.537 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///godata/pipelines/JS-LSP-Tests/data/steps-codecomplete/specs/codecomplete_step.spec","diagnostics":[{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":24}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"},{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":22}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"},{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":24}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"}]}
01:17:38.540 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///godata/pipelines/JS-LSP-Tests/data/steps-codecomplete/specs/codecomplete_param.spec","diagnostics":[{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"},{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"},{"range":{"start":{"line":7,"character":0},"end":{"line":7,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"},{"range":{"start":{"line":8,"character":0},"end":{"line":8,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"},{"range":{"start":{"line":9,"character":0},"end":{"line":9,"character":10000}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"}]}
01:17:38.540 <-- notif: textDocument/publishDiagnostics: {"uri":"file:///godata/pipelines/JS-LSP-Tests/data/steps-codecomplete/specs/codecomplete_step.spec","diagnostics":[{"range":{"start":{"line":4,"character":0},"end":{"line":4,"character":24}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"},{"range":{"start":{"line":5,"character":0},"end":{"line":5,"character":22}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"},{"range":{"start":{"line":6,"character":0},"end":{"line":6,"character":24}},"severity":1,"message":"write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"}]}
01:17:38.625 --> request #2: textDocument/completion: {"position":{"line":5,"character":18},"textDocument":{"uri":"file:///godata/pipelines/JS-LSP-Tests/data/steps-codecomplete/specs/codecomplete_step.spec"}}
01:17:38.626 request #2: textDocument/completion: failed to get steps from runner. Error while connecting to runner : write tcp 127.0.0.1:40738->127.0.0.1:36616: use of closed network connection
01:17:38.626 <-- notif: window/logMessage: {"type":1,"message":"request #2: textDocument/completion: failed to get steps from runner. Error while connecting to runner : write tcp 127.0.0.1:40738-\u003e127.0.0.1:36616: use of closed network connection"}
01:17:38.626 <-- result #2: textDocument/completion: {"isIncomplete":false,"items":[{"label":"start \u003cs\u003e","kind":3,"detail":"Step","documentation":"start \u003cs\u003e","filterText":"start \u003cs\u003e","textEdit":{"range":{"start":{"line":5,"character":2},"end":{"line":5,"character":22}},"newText":"start \"${0:s}\""},"insertTextFormat":2},{"label":"two \u003canother\u003e \u003cparameter\u003e","kind":3,"detail":"Step","documentation":"two \u003canother\u003e \u003cparameter\u003e","filterText":"two \u003canother\u003e \u003cparameter\u003e","textEdit":{"range":{"start":{"line":5,"character":2},"end":{"line":5,"character":22}},"newText":"two \"${1:another}\" \"${0:parameter}\""},"insertTextFormat":2},{"label":"start one \u003cone\u003e","kind":3,"detail":"Step","documentation":"start one \u003cone\u003e","filterText":"start one \u003cone\u003e","textEdit":{"range":{"start":{"line":5,"character":2},"end":{"line":5,"character":22}},"newText":"start one \"${0:one}\""},"insertTextFormat":2},{"label":"unimplemented step three","kind":3,"detail":"Step","documentation":"unimplemented step three","filterText":"unimplemented step three","textEdit":{"range":{"start":{"line":5,"character":2},"end":{"line":5,"character":22}},"newText":"unimplemented step three"},"insertTextFormat":2},{"label":"unimplemented step one","kind":3,"detail":"Step","documentation":"unimplemented step one","filterText":"unimplemented step one","textEdit":{"range":{"start":{"line":5,"character":2},"end":{"line":5,"character":22}},"newText":"unimplemented step one"},"insertTextFormat":2},{"label":"implemented step one","kind":3,"detail":"Step","documentation":"implemented step one","filterText":"implemented step one","textEdit":{"range":{"start":{"line":5,"character":2},"end":{"line":5,"character":22}},"newText":"implemented step one"},"insertTextFormat":2},{"label":"unimplemented step two","kind":3,"detail":"Step","documentation":"unimplemented step two","filterText":"unimplemented step two","textEdit":{"range":{"start":{"line":5,"character":2},"end":{"line":5,"character":22}},"newText":"unimplemented step two"},"insertTextFormat":2},{"label":"one \u003csomething\u003e","kind":3,"detail":"Step","documentation":"one \u003csomething\u003e","filterText":"one \u003csomething\u003e","textEdit":{"range":{"start":{"line":5,"character":2},"end":{"line":5,"character":22}},"newText":"one \"${0:something}\""},"insertTextFormat":2}]}
01:17:38.633 --> request #3: shutdown: null
01:17:38.634 <-- result #3: shutdown: null
01:17:38.634 --> notif: exit: null
```

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 4/5/18

**Comment by sguptatw** [comment]
Getting the error `Failed to initialize scenario datastore. Error: write tcp 127.0.0.1:56353->127.0.0.1:56355: use of closed network connection` on running the project mentioned in the original issue.
```
.../.gauge/plugins/js/2.3.0.nightly-2018-05-08/src/executor.js:46
  new Test(step.fn, parameters, timeout).run().then(
                ^

TypeError: Cannot read property 'fn' of undefined
    at Object.executeStep [as step] (.../.gauge/plugins/js/2.3.0.nightly-2018-05-08/src/executor.js:46:17)
    at MessageProcessor.executeStep (.../.gauge/plugins/js/2.3.0.nightly-2018-05-08/src/message-processor.js:39:26)
    at MessageProcessor.getResponseFor (.../.gauge/plugins/js/2.3.0.nightly-2018-05-08/src/message-processor.js:316:40)
    at ExecutionConnection.<anonymous> (.../.gauge/plugins/js/2.3.0.nightly-2018-05-08/src/gauge.js:43:19)
    at ExecutionConnection.emit (events.js:182:13)
    at Socket.messageHandler (.../.gauge/plugins/js/2.3.0.nightly-2018-05-08/src/connection.js:20:12)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
            
            Failed Step: jhhjkhjk
            Specification: .../Downloads/basic9 3/specs/specs4/example.spec
            Error Message: Connection closed [127.0.0.1:58924] cause: EOF
            Stacktrace: 
            
            Error Message: write tcp 127.0.0.1:58922->127.0.0.1:58924: use of closed network connection
            Stacktrace: 
            
    Error Message: write tcp 127.0.0.1:58922->127.0.0.1:58924: use of closed network connection
    Stacktrace: 
    
  ## Vowel counts in multiple word
Failed to initialize scenario datastore. Error: write tcp 127.0.0.1:58922->127.0.0.1:58924: use of closed network connection
    Error Message: write tcp 127.0.0.1:58922->127.0.0.1:58924: use of closed network connection
    Stacktrace: 
    

    Error Message: write tcp 127.0.0.1:58922->127.0.0.1:58924: use of closed network connection
    Stacktrace: 
```

**Comment by sguptatw** [comment]
Fixed in version
```
Gauge version: 0.9.9.nightly-2018-05-04
Commit Hash: 886dc10

Plugins
-------
html-report (4.0.4.nightly-2018-04-11)
js (2.3.1.nightly-2018-05-08)
```

**Comment by boomi243** [comment]
Hi Soumya,

I installed nightly build but it is still not working for me.

{ Error: Response already processed.
    at _enqueueCommand (c:\MyWork\gauge_taiko\node_modules\chrome-remote-interface\lib\chrome.js:89:34)
    at Chrome._handleMessage (c:\MyWork\gauge_taiko\node_modules\chrome-remote-interface\lib\chrome.js:245:17)
    at WebSocket._ws.on (c:\MyWork\gauge_taiko\node_modules\chrome-remote-interface\lib\chrome.js:223:22)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage (c:\MyWork\gauge_taiko\node_modules\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (c:\MyWork\gauge_taiko\node_modules\ws\lib\Receiver.js:389:14)
    at perMessageDeflate.decompress (c:\MyWork\gauge_taiko\node_modules\ws\lib\Receiver.js:349:40)
    at _decompress (c:\MyWork\gauge_taiko\node_modules\ws\lib\PerMessageDeflate.js:306:9)
    at _inflate.flush (c:\MyWork\gauge_taiko\node_modules\ws\lib\PerMessageDeflate.js:386:7)
    at afterWrite (_stream_writable.js:480:3)
  request:
   { method: 'Network.continueInterceptedRequest',
     params: { interceptionId: 'id-1' } },
  response: { code: -32602, message: 'Response already processed.' } }
Error ----------------------------------

Connection to runner with Pid 5868 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.1:54930->127.0.0.1:54933: use of closed network connection

**Comment by boomi243** [comment]
Thanks for the update Srikanth. I will try it and let you know. 

Do I need to install latest html report as well?

**Comment by sriv** [comment]
Yes, that will bring all the fixes/features released in html-report as well. 

In general, we recommend that you use the latest versions of gauge + plugins.

**Comment by boomi243** [comment]
Sure Thanks. I will keep you posted
