### ISSUE TITLE
Unable to require `js` files in step implementations using gauge-js v2.3.6

### ISSUE THREAD

**Issue by sauravsr** [getgauge/gauge-js#271]
**Description of the problem**
There seems to a problem with gauge-js plugin v2.3.6 where this #246  has been addressed.

Check this code [here](https://github.com/getgauge/gauge-js/blob/master/src/req-manager.js#L39).
So the scenario goes like this,
I have a `step_implementation.js` that has the require statements as below:
```
const x = require('url');
const y = require("@scope/package-name");
const z = require("../../lib/example"); // Note: example is a .js file (example.js) and not a directory
```
For x and y(for which the fix has been implemented) case, the check fs.existsSync(relativePath) works fine but for z case , the same check breaks because it assumes that example is a directory and not a .js file and because of this I started to get the error ` Unable to require module '../../lib/example'` for z cases.

Our step implementations, uses several supporting libraries within the project and we have imported them in implementation file as in the code snippet that has started to fail with the latest gauge-js plugin v2.3.6.

**Comment by Apoorva-GA** [comment]
@sauravsr I could replicate the issue. Thanks for reporting.
We will fix it soon.

**Comment by sauravsr** [comment]
closing this PR as the issue has been fixed with this commit - https://github.com/getgauge/gauge-js/commit/f0ce9e23b348d46678f86154a111911cc4467ee7

**Comment by sauravsr** [comment]
Closing this issue as this has been fixed with this commit - https://github.com/getgauge/gauge-js/commit/f0ce9e23b348d46678f86154a111911cc4467ee7

**Comment by sauravsr** [comment]
When shall we expect the new release of gauge-js plugin v2.3.7 ?
@Apoorva-GA ?

**Comment by nehashri** [comment]
@sauravsr This issue still needs to go through our QA. Reopening it for that. 
We will be making a release of gauge-js soon.

**Comment by Debashis9012** [comment]
This issue has been tested and found fixed.
Tested version: `b9d1cdcc`

**Comment by h2grover** [comment]
@Debashis9012 is this fix deployed yet?

**Comment by BugDiver** [comment]
@h2grover @sauravsr The fix has been deployed. Please update the plugin by running `gauge update js`.
